steps:
  # Build the docker images:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','us-central1-docker.pkg.dev/sublime-state-413617/test-telecom-prediction/test_telecom_predictions:$COMMIT_SHA','.']

  # Run Test cases
#
#  - name: 'us-central1-docker.pkg.dev/sublime-state-413617/test-telecom-prediction/telecom_predictions:$COMMIT_SHA'
#    entrypoint: python
#    args: ['-m','pytest','.']

  # Push the docker image to artifact

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/sublime-state-413617/test-telecom-prediction/test_telecom_predictions:$COMMIT_SHA']

  # Deploy Cloud Run Service

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'test-telecom-prediction'
      - '--image'
      - 'us-central1-docker.pkg.dev/sublime-state-413617/test-telecom-prediction/test_telecom_predictions:$COMMIT_SHA'
      - '--region'
      - 'us-central1'

options:
 logging : CLOUD_LOGGING_ONLY
